/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/confirm-password': RouteRecordInfo<'/auth/confirm-password', '/auth/confirm-password', Record<never, never>, Record<never, never>>,
    '/auth/forgot-password': RouteRecordInfo<'/auth/forgot-password', '/auth/forgot-password', Record<never, never>, Record<never, never>>,
    '/auth/Login': RouteRecordInfo<'/auth/Login', '/auth/Login', Record<never, never>, Record<never, never>>,
    '/auth/Register': RouteRecordInfo<'/auth/Register', '/auth/Register', Record<never, never>, Record<never, never>>,
    '/auth/reset-password': RouteRecordInfo<'/auth/reset-password', '/auth/reset-password', Record<never, never>, Record<never, never>>,
    '/auth/reset-password/[token]': RouteRecordInfo<'/auth/reset-password/[token]', '/auth/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/auth/two-factor-challenge': RouteRecordInfo<'/auth/two-factor-challenge', '/auth/two-factor-challenge', Record<never, never>, Record<never, never>>,
    '/auth/verify-email': RouteRecordInfo<'/auth/verify-email', '/auth/verify-email', Record<never, never>, Record<never, never>>,
    '/Dashboard': RouteRecordInfo<'/Dashboard', '/Dashboard', Record<never, never>, Record<never, never>>,
    '/settings/appearance': RouteRecordInfo<'/settings/appearance', '/settings/appearance', Record<never, never>, Record<never, never>>,
    '/settings/password': RouteRecordInfo<'/settings/password', '/settings/password', Record<never, never>, Record<never, never>>,
    '/settings/Profile': RouteRecordInfo<'/settings/Profile', '/settings/Profile', Record<never, never>, Record<never, never>>,
    '/settings/two-factor': RouteRecordInfo<'/settings/two-factor', '/settings/two-factor', Record<never, never>, Record<never, never>>,
  }
}
